{{- if .Values.ingress.enabled -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "compare.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - backend:
            serviceName: {{ $.Values.service.name }}
            servicePort: 4440
          path: /
    {{- end }}
  {{ if .Values.ingress.tls -}}
  tls:
  - hosts:
    {{- range $host := .Values.ingress.hosts }}
    - {{ $host }}
    secretName: {{ $.Values.service.name }}
    {{- end }}
  {{ end -}}
{{- end -}}
