# Default values for janusui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
team: SRE
replicaCount: 1
namespace:
  name: spacerundeck
image:
  repository: 162790430163.dkr.ecr.us-east-1.amazonaws.com/docker_rundeck
  tag: latest
  pullPolicy: IfNotPresent
probe:
  liveness:
    initialDelaySeconds: 120
  readiness:
    initialDelaySeconds: 120
service:
  name: rundeck
  type: ClusterIP 
  externalPort: 4440
  internalPort: 4440
#configmap:
#  app_session_state: testbed
#  janus_via_suffix: .brooklyn.aspect-cloud.net/manux
#  #Fix: This isnt over 443.  The ingress on forgerock-dev is for port 80
#  janus_ig_url: http://openig.forgerock-dev.ops.aspect-cloud.net
#  janus_backend_url: https://janusapi:8443/
#  mercury_backend_url: https://mercury/
#  janus_ui_host:  myaspect.k8s.ops.aspect-cloud.net
#volumeMount:
#  mountPath: /var/janus/ui
#  name: nginx-ssl
#volumes:
#  name: nginx-ssl
#  path: /etc/nginx/ssl
hpa:
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - rundeck.iad1.sre.aspect-cloud.net
  annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/acme-challenge-type: dns01
      certmanager.k8s.io/acme-dns01-provider: route53
  tls:
     - secretName: rundeck.iad1.sre.aspect-cloud.net
       hosts:
         - rundeck.iad1.sre.aspect-cloud.net
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
